#!/bin/bash
if [ -z "$1" ]
then
	cat <<EOH
Please use: $0 <key to compare> [seed]
	compare:	all, Words, salt, coeff, secret, encrypted, Data, 'private key'
	seed:		optional use a own seed phrase
EOH
	exit 1
fi

if [ -n "$2" ]
then
	SEED="$2"
else
	SEED='label cart fee spice decorate next holiday stand mom clown cool huge repeat expire giraffe own'
fi

VALUE=$1
PYTHON_CMD='python -m polyseed recover'
C_CMD='./compare-tools/polyseed-recover'

if [ "$VALUE" = "all" ]
then
	for value in Words salt coeff secret encrypted Data 'private key'
	do
		$0 "$value" "$SEED" 
	done
	exit 0
fi

PYTHON=$($PYTHON_CMD "$SEED" | grep "$VALUE")
C=$($C_CMD "$SEED" | grep "$VALUE")

VALUE_P=$(echo -n "$PYTHON" | sed -e "s/^${VALUE}:\s*//")
VALUE_C=$(echo -n "$C" | sed -e "s/^${VALUE}:\s*//")
if [ "${VALUE_P}" = "${VALUE_C}" ]
then
	echo -e "${VALUE}: ${VALUE_P}: OK"
	exit 0
else
	echo -e "expected: ${C}: FAILED\ngot:      ${PYTHON}"
	exit 1
fi
